#!/usr/bin/bash

start_corenlp_server() {
   cd build/stanford-corenlp*
   java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -preload tokenize,ssplit,pos,lemma,ner,parse,depparse -status_port 9000 -port 9000 -timeout 15000 > /dev/null 2>&1
}

start_corenlp_server &
echo "Waiting Stanford CoreNLP Server to launch on 9000..."
while ! nc -z localhost 9000; do   
  sleep 0.1 # busy waiting
done
echo "Server launched"
echo "Executing test..."
python3 test.py
pkill -f StanfordCoreNLPServer
echo 'FINISHED'
